---
- name: AUTOMATIC BACKUP OF STARTUP-CONFIG
  hosts: CSR1kv
  gather_facts: false
  connection: local
 
  tasks:
    - name: DISPLAYING THE STARTUP-CONFIG
      ios_command:
        commands: 
          - show startup-config 
      register: config
    - name: SAVE OUTPUT TO ./backups/
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "backups/startup_backup.txt"