---
- name: SET IPv6
  hosts: CSR1kv
  gather_facts: false
  connection: local

  tasks:
  - name: SET IPv6 of Gigabit Eth 1
    ios_command:
      commands:
        - configure terminal
        - interface GigabitEthernet1
        - ipv6 address 2001:db8:acad:1::1/64
        - ipv6 address fe80::1:1 link-local